### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ghost** [offbye/cordova-plugin-x5engine-webview#3]
ionic  v2.1.1
Cordova 6.4.0
win 10 64x
node  v5.10.1

执行cordova build android 遇到个错误

---------------------

`Error: cmd: Command failed with exit code 1 Error output:
ע: ĳЩ�����ļ�ʹ�û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ�û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
D:\code\app2\platforms\android\src\org\apache\cordova\x5engine\X5WebViewEngine.java:58: ����: X5WebViewEngine��� ǳ�����, ����δ����CordovaWebViewEngine�еĳ����evaluateJavascript(String,ValueCallback<String>)
public class X5WebViewEngine implements CordovaWebViewEngine {
          ^
ע: ĳЩ�����ļ�ʹ�û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
1 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

---------------------------------
\platforms\android\build\outputs\logs\manifest-merger-armv7-debug-report.txt
日志如下:

`-- Merging decision tree log ---
manifest
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:2:1-18:12
	package
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:2:98-138
		INJECTED from D:\code\app2\platforms\android\AndroidManifest.xml
		INJECTED from D:\code\app2\platforms\android\AndroidManifest.xml
	android:versionName
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:2:70-97
		INJECTED from D:\code\app2\platforms\android\AndroidManifest.xml
		INJECTED from D:\code\app2\platforms\android\AndroidManifest.xml
	android:hardwareAccelerated
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:2:11-45
	android:versionCode
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:2:46-69
		INJECTED from D:\code\app2\platforms\android\AndroidManifest.xml
		INJECTED from D:\code\app2\platforms\android\AndroidManifest.xml
	xmlns:android
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:2:139-197
supports-screens
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:3:5-191
	android:largeScreens
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:3:49-76
	android:smallScreens
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:3:132-159
	android:normalScreens
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:3:77-105
	android:xlargeScreens
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:3:160-188
	android:resizeable
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:3:106-131
	android:anyDensity
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:3:23-48
uses-permission#android.permission.INTERNET
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:4:5-67
	android:name
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:4:22-64
application
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:5:5-12:19
MERGED from [com.android.support:support-v4:24.1.1] D:\code\app2\platforms\android\build\intermediates\exploded-aar\com.android.support\support-v4\24.1.1\AndroidManifest.xml:25:5-20
	android:label
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:5:81-113
	android:supportsRtl
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:5:114-140
	android:hardwareAccelerated
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:5:18-52
	android:icon
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:5:53-80
activity#com.ionicframework.myapp743247.MainActivity
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:6:9-11:20
	android:label
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:6:97-134
	android:launchMode
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:6:135-165
	android:windowSoftInputMode
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:6:257-299
	android:configChanges
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:6:19-96
	android:theme
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:6:194-256
	android:name
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:6:166-193
intent-filter#android.intent.action.MAIN+android.intent.category.LAUNCHER
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:7:13-10:29
	android:label
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:7:28-65
action#android.intent.action.MAIN
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:8:17-69
	android:name
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:8:25-66
category#android.intent.category.LAUNCHER
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:9:17-77
	android:name
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:9:27-74
uses-sdk
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:13:5-74
MERGED from [org.xwalk:xwalk_core_library:21.51.546.7] D:\code\app2\platforms\android\build\intermediates\exploded-aar\org.xwalk\xwalk_core_library\21.51.546.7\AndroidManifest.xml:6:5-8:41
MERGED from [com.android.support:support-v4:24.1.1] D:\code\app2\platforms\android\build\intermediates\exploded-aar\com.android.support\support-v4\24.1.1\AndroidManifest.xml:21:5-23:54
MERGED from [android:CordovaLib:unspecified:debug] D:\code\app2\platforms\android\build\intermediates\exploded-aar\android\CordovaLib\unspecified\debug\AndroidManifest.xml:25:5-44
	tools:overrideLibrary
		ADDED from [com.android.support:support-v4:24.1.1] D:\code\app2\platforms\android\build\intermediates\exploded-aar\com.android.support\support-v4\24.1.1\AndroidManifest.xml:23:9-51
	android:targetSdkVersion
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:13:42-71
	android:minSdkVersion
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:13:15-41
		INJECTED from D:\code\app2\platforms\android\AndroidManifest.xml
		INJECTED from D:\code\app2\platforms\android\AndroidManifest.xml
uses-permission#android.permission.ACCESS_NETWORK_STATE
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:14:5-79
	android:name
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:14:22-76
uses-permission#android.permission.ACCESS_WIFI_STATE
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:15:5-76
	android:name
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:15:22-73
uses-permission#android.permission.WRITE_EXTERNAL_STORAGE
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:16:5-81
	android:name
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:16:22-78
uses-permission#android.permission.READ_PHONE_STATE
ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:17:5-75
	android:name
		ADDED from D:\code\app2\platforms\android\AndroidManifest.xml:17:22-72
`

**Comment by gyf19** [comment]
@offbye   遇到相同问题，请楼主回复

**Comment by lyloou** [comment]
cordova 6.0之后的`CordovaWebViewEngine`接口增加了`evaluateJavascript()`方法，
`X5WebViewEngine.java`实现了这个接口，但是却没有这个方法，所以会导致`build`出错。

可以在`X5WebViewEngine`类中添加如下代码解决这个问题：
``` java
    @Override
    public void evaluateJavascript(String js, android.webkit.ValueCallback<String> callback) {
        if (callback instanceof com.tencent.smtt.sdk.ValueCallback) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                webView.evaluateJavascript(js, (com.tencent.smtt.sdk.ValueCallback<String>) callback);
            } else {
                LOG.d(TAG, "This webview is using the old bridge");
            }
        }
    }
```

**Comment by w577186465** [comment]
我也遇到了同样的问题

**Comment by surmnt** [comment]
有已解决了问题的么？

**Comment by beijianqiang** [comment]
这个问题要怎么解决

**Comment by beijianqiang** [comment]
@offbye

**Comment by zsxsoft** [comment]
https://github.com/zsxsoft/cordova-plugin-x5-tbs
Fixed
