### ISSUE TITLE
Cordova 6.4.0问题

### ISSUE THREAD

**Issue by skyammk** [offbye/cordova-plugin-x5engine-webview#4]
使用Cordova 6.4.0版本create新App，直接添加该插件后，使用cordova build命令报错，如下：
`
> Error: cmd: Command failed with exit code 1 Error output: -Xlint:deprecation 
> D:\hello\hello\platforms\android\src\org\apache\cordova\x5engine\X5WebViewEngine.java:58:
X5WebViewEngine
> CordovaWebViewEngine.evaluateJavascript(String,ValueCallback<String>)
> public class X5WebViewEngine implements CordovaWebViewEngine {
> D:\hello\hello\platforms\android\src\org\apache\cordova\x5engine\X5WebChromeClient.javaʹ API -Xlint:deprecation

> FAILURE: Build failed with an exception.

> What went wrong:
> Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

> Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log > output.

我手动拷贝x5engine文件夹至org/apache/cordova/ 目录下，手动override‘evaluateJavascript‘方法，并且在config.xml中添加相应配置后，可以build出apk文件，但是App运行时前台js报错：

> deviceready has not fired after 5 seconds
> Channel not fired: onCordovaInfoReady
> Channel not fired: onFileSystemPathReady
> Channel not fired: onCordovaConnectionReady
'

**Comment by zsxsoft** [comment]
你解决了吗？

**Comment by zsxsoft** [comment]
哎，我的解决办法见我的Fork: https://github.com/zsxsoft/cordova-plugin-x5engine-webview
顺便也把它升到了tbs 3.0
